### ISSUE TITLE
Add columns: `last_update_date` and `submission_date`

### ISSUE THREAD

**Issue by Khoroshevskyi** [pepkit/pepdbagent#62]
Add two additional columns to database table: 

- [x] `last_update_date`
- [x]  `submission_date`

While udate date information is stored in annot_table, it's inefficient and sql syntax complicated to update this value every time we update project

**Comment by nleroy917** [comment]
Hey this is great! Super helpful for pephub. It would be even better if the `last_update` were initialized as the `submission_date` when inserted into the database. As an example, I just submitted this basic PEP, and when fetching info from the database, this is the JSON:

![image](https://user-images.githubusercontent.com/41063083/211838823-d6919fcf-84a8-4586-9112-417a5b284951.png)

Not that big of a deal since you can add logic to use submission data if last update is null, but would be convenient to init the last_update with the submission date.

**Comment by Khoroshevskyi** [comment]
This is some I think, this is a bug, because everything was working for me.
Where exactly in the code do you have this issue?
